### PR TITLE
Remove unused oauth import.

### PR DESCRIPTION
**Pull request by superfrink**
Addresses issue #15 .

### CODE REVIEW

**Comment by aggieben** [comment]
It appears that the build fails with this change...did you mean to submit this?

**Comment by superfrink** [comment]
That is interesting.  I used the code and installed it without problem using:

    go get github.com/superfrink/trello
   
The failure looks to be related to a different repository used in the CI:

    warning: code.google.com is shutting down; import path code.google.com/p/go.tools/cmd/cover will stop working
    the code.google.com/p/go.tools/cmd/cover command has moved; use golang.org/x/tools/cmd/cover instead.
    The command "go get code.google.com/p/go.tools/cmd/cover" failed and exited with 1 during .

How/where is the CI set up?

**Comment by superfrink** [comment]
I updated .travis.yml to remove the reference to code.google.com.  CI tests are passing now.

**Comment by aggieben** [comment]
Thanks!

**Pull request merged**
